### ISSUE TITLE
cst df -u  does work for user dazhoutest@mailinator.com

### ISSUE THREAD

**Issue by 10097zhou** [hagemt/node-cisco-webex-tools#23]
~$ cst df -u dazhoutest@mailinator.com
Error: no such person: dazhoutest@mailinator.com
    at getUniquePerson (/usr/local/lib/node_modules/ciscospark-tools/scripts/developer-features.js:39:8)
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:118:7)

Error: Abnormal script termination!
    at Object.<anonymous> (/usr/local/lib/node_modules/ciscospark-tools/scripts/index.js:20:23)
    at Module._compile (module.js:649:30)
    at Object.Module._extensions..js (module.js:660:10)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:501:12)
    at Function.Module._load (module.js:493:3)
    at Function.Module.runMain (module.js:690:10)
    at startup (bootstrap_node.js:194:16)
    at bootstrap_node.js:666:3

	Error message(s) above may be due to bugs in the npm package: ciscospark-tools

	If so, please file a GitHub issue (with full reproduction steps) here:

	https://github.com/hagemt/node-ciscospark-tools/issues

**Comment by hagemt** [comment]
Note to self: need to review stability of `-u` w/ `cst df` before 0.8 release. Thanks!
